version: '3.9'

services:

  mysql:
    # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
    # platform: linux/x86_64
    container_name: snce-pokemon-db
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - snce-pokemon-db:/var/lib/mysql
      # - ./snce-pokemon-db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: curl -f snce-pokemon-db:${DB_PORT}
      interval: 3s
      timeout: 2s
      retries: 10
    networks:
      - default

  nginx:
    container_name: snce-pokemon-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: snce-pokemon-nginx:latest
    ports:
      - ${APP_PORT}:80
    depends_on:
      app: 
        condition: service_started

  app:
    container_name: snce-pokemon-app
    build:
      context: ./
      dockerfile: Dockerfile
      target: run
    image: snce-pokemon-app:latest
    command: dev
    restart: unless-stopped
    env_file: .env
    # ports:
    #   - ${APP_PORT}:${APP_PORT}
    stdin_open: true
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/next-app
    networks:
      - default

volumes: 
  snce-pokemon-db:

networks:
  default: