import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from './createPage.module.scss'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { PokemonTeam } from '@/components'
import { Button } from '@/components/atoms'
import { pokemonService } from '@/services'
import type { IPokemon } from '@/types/models/Pokemon'
import { getRandomInt } from '@/utils/number'

// const inter = Inter({ subsets: ['latin'] })

export default function CreateTeam() {
  const [pokemon, setPokemon] = useState<IPokemon | undefined>()
  const [team, setTeam] = useState<IPokemon[]>([])
  console.log(team)

  const getRandomPokemon = async () => {
    const id = getRandomInt(1, 500)

    await fetch(`/api/pokemon/${id}`, {
      method: 'GET',
    })
      .then((res: Response) => {
        return res.json()
      })
      .then((pokemon: IPokemon | undefined) => {
        if (pokemon) setTeam([...team, pokemon])
      })
      .catch((error) => console.log(error))
  }
  return (
    <>
      <Head>
        <title>PT | Create new team</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles['create-team-page']}>
        <PokemonTeam team={team} />
        <Button onClick={getRandomPokemon} action="Gotta cath 'em all!" />
      </main>
    </>
  )
}
