import Head from 'next/head'
import styles from './createPage.module.scss'
import { useState } from 'react'
import { PokemonTeam } from '@/components'
import { Button } from '@/components/atoms'
import type { Pokemon } from '@/types/models/Pokemon'
import { getRandomInt } from '@/utils/number'

// const inter = Inter({ subsets: ['latin'] })

export default function CreateTeam() {
  // const [pokemon, setPokemon] = useState<Pokemon | undefined>()
  const [team, setTeam] = useState<Pokemon[]>([])

  const getRandomPokemon = async () => {
    const id = getRandomInt(1, 500)

    await fetch(`/api/pokemon/${id}`, {
      method: 'GET',
    })
      .then((res: Response) => {
        return res.json()
      })
      .then((pokemon: Pokemon | undefined) => {
        console.log(pokemon)
        if (pokemon) setTeam([...team, pokemon])
      })
      .catch((error) => console.log(error))
  }

  const createTeam = async () => {
    await fetch(`/api/team/pippo`, {
      method: 'POST',
    }).catch((error) => console.log(error))
  }
  return (
    <>
      <Head>
        <title>PT | Create new team</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles['create-team-page']}>
        <PokemonTeam team={team} />
        <Button onClick={getRandomPokemon} action="Gotta cath 'em all!" />
        <Button onClick={createTeam} action="Create new team" />
      </main>
    </>
  )
}
